# Bionic stuff
BOARD_GLOBAL_CFLAGS += -DDISABLE_ASHMEM_TRACKING
BOARD_USES_LEGACY_MMAP := true
MALLOC_SVELTE := true
LIBART_IMG_BASE := 0x30000000
TARGET_NEEDS_PLATFORM_TEXT_RELOCATIONS := true

TARGET_ENABLE_NON_PIE_SUPPORT := true
LINKER_NON_PIE_EXECUTABLES_HEADER_DIR := device/samsung/aries-common/include